# Generated by Django 5.0.4 on 2024-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNR', models.URLField()),
                ('ClientName', models.CharField(max_length=100)),
                ('CaseStatus', models.CharField(max_length=50)),
                ('CaseType', models.CharField(max_length=50)),
                ('Doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('ApplytoVC', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNR', models.URLField(max_length=16)),
                ('CaseStatus', models.CharField(max_length=50)),
                ('Lawyer_1', models.CharField(max_length=100)),
                ('Lawyer_2', models.CharField(max_length=100)),
                ('Lawyer1ASVC', models.BooleanField(default=False)),
                ('Lawyer2ASVC', models.BooleanField(default=False)),
                ('Approve', models.URLField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNR', models.URLField(max_length=16)),
                ('CaseStatus', models.CharField(max_length=50)),
                ('Lawyer_1', models.CharField(max_length=100)),
                ('Lawyer_2', models.CharField(max_length=100)),
                ('virtualcourt', models.URLField(default=False)),
            ],
        ),
    ]
