# Generated by Django 5.0.4 on 2024-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JusticeFY_app', '0002_lawyer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='ApplytoVC',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='CNR',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='physicaljudge',
            name='Approve',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='physicaljudge',
            name='CNR',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='virtualjudge',
            name='CNR',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='virtualjudge',
            name='virtualcourt',
            field=models.CharField(max_length=200),
        ),
    ]
